### PR TITLE
Update link to Minecraft Wiki

### PR DESCRIPTION
**Pull request by ghost**
Minecraft Wiki has officially moved from Fandom to their own wiki. I updated a link I found in a comment.

### CODE REVIEW

**Comment by eristhea** [comment]
since that's code from Fabric, it's not our job to update it. changing the link would just create one more merge conflict to deal with when we sync from upstream! you can cherry-pick this over to FAPI.

**Comment by EnnuiL** [comment]
No! We do accept tiny merge conflicts like that! I would reopen this but I can't

**Comment by eristhea** [comment]
sorry, thought it would be best to just have the commit on fabric

**Comment by ghost** [comment]
Try now? Anyway I've submitted it to Fabric too so it will hopefully not be a conflict.

**Review by EnnuiL — APPROVED** [review]

**Comment by TheGlitch76** [comment]
Superceded by #134 which includes 68c3a29b6b5a34f3317fc3bf99a0e5c5e3a0a7c1

**Pull request closed without merging**
