### PR TITLE
Update to 1.20.2

### PR DESCRIPTION
**Pull request by TheGlitch76**
Make sure this is a merge and not a rebase/squash.

### CODE REVIEW

**Comment by Santiag09** [comment]
any update on when 1.20.2 releases???

**Comment by Pdam67** [comment]
> any update on when 1.20.2 releases???

Give it time bro, Please.

Just because there hasn't been many commits in recent times doesn't mean they aren't working on it at all.

**Comment by OroArmor** [comment]
Correct. A change was made to QSL that doesn't really work with FAPI, so we are figuring out a way to fix this. As well the two current maintainers are very busy.

**Comment by DovydasTEDS** [comment]
Has there been any progress?

Thanks developers for trying to make this work.

**Comment by OroArmor** [comment]
Yes. I have working code that will be pushed into this PR soon

**Comment by OroArmor** [comment]
superceeded

**Pull request closed without merging**
