### PR TITLE
Sync QFAPI 1.20.1 with Fabric API 0.92.2

### LINKED ISSUE #149: UpStream Sync for 1.20.1 => Including FAPI 0.92.0
FAPI 0.92.0 was just released, and backported a few things like mob conversion event and more importantly the Data Attachment API.

I can't add the "upstream sync" label by myself, waiting on writer access holders for that.

### PR DESCRIPTION
**Pull request by EnnuiL**
Fixes #149.
What does this do?
- Makes QFAPI actually usable on 1.20.1
- Fixes minor mistakes caused by Messiness™
- Y'all wanna More Maintainable QFAPI? Here is it! (seriously, sorry for making it quite hellish to work with)
  - Disable Machete in order to avoid Going Crazy (RIP near-1 MB savings though..)
  - Automated setting each subproject's `base.archivesName`
  - Reduced divergences with FAPI on certain spots
  - Updates stuff (updated stuff is good)
  - Partially fixes broken CI (Client tests work, server doesn't due to mandatory Fabric Installer)
  - The Spotless machine has been activated (hence the weird tabs)
  - ..and much more!
  
please double-check this code though, it could blow up maybe
(also please don't make me devour anybody within this premise)

### CODE REVIEW

**Comment by ImBehinYa** [comment]
so will theire be update or is quilted fabric dead?

**Comment by eristhea** [comment]
I intend to test and release this tonight ^^

**Review by eristhea — APPROVED** [review]
looks great! tested with no issues

**Comment by eristhea** [comment]
@OroArmor do you still want to take a look before merge?

**Comment by OroArmor** [comment]
Sure. I'll review in the next 24 hours.

**Review by OroArmor — APPROVED** [review]
Gave a quick review. Seems good. LGTM!

**Pull request merged**
