### PR TITLE
Sync 1.19.2 to 0.77.0

### PR DESCRIPTION
**Pull request by unilock**
Everything seems to be OK in a production environment with over 500 mods :)

(hopefully I did this right)

### CODE REVIEW

**Comment by unilock** [comment]
The workflow is failing because the licenses are outdated. I wasn't sure whether I should run the licenser task.

**Review by eristhea — APPROVED** [review]
just run `applyLicenses` and it'll all be fixed for you!

**Comment by unilock** [comment]
I wonder if it would be better to wait three days, so it doesn't fail again next year :v

**Comment by OroArmor** [comment]
The license change seems wrong but i dont want to fight the old licenser so ill set it go. Everything else looks good

**Comment by LDev-IX** [comment]
Any idea on when it will be merged?

**Comment by eristhea** [comment]
tested, looks great!

**Pull request merged**
